version = 0.1
[default.deploy.parameters]
stack_name = "qaservice"
resolve_s3 = true
s3_prefix = "qaservice"
region = "ap-northeast-1"
profile = "Student-753695775301"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
